### ISSUE TITLE
any detach is not required?

### ISSUE THREAD

**Issue by e0jun** [Lily-Le/EcoTTA#3]
Thank you for re-implementing EcoTTA.

In my understanding, we need a detach module for not storing intermediate activations.
Is it right? 

Thank you in advance!

**Comment by Lily-Le** [comment]
Hi. The detach module is implemented in class one_part_of_networks(Module) defined in ecotta_models.  Hope this can answer your question. Feel free to ask me if you have any further questions :D

**Comment by e0jun** [comment]
Thank you for your quick reply:)
