### ISSUE TITLE
[ERROR] _pickle.UnpicklingError when loading a model

### ISSUE THREAD

**Issue by ShunyaYamagami** [Lily-Le/EcoTTA#4]
Thanks for sharing the code.

I did not change anything in the code and tried to run it with the arguments as per the README, but when loading the model (robustbench/utils.py l.123) I got the following error
The model path points to `PosixPath('robust_models/cifar100/corruptions/Hendrycks2020AugMix_WRN.pt')`
pointing to the `Hendrycks2020AugMix_WRN.pt'.

Can you please check if there is a problem with the file?

```
  File "main.py", line 26, in <module>
    from ecotta_models.wideresnet28 import ecotta_networks as ecotta_networks_wrs28
  File "EcoTTA/ecotta_models/wideresnet28.py", line 11, in <module>
    base_model = load_model('Standard', './robust_models', 'cifar10', ThreatModel.corruptions).cuda()
  File "EcoTTA/robustbench/utils.py", line 123, in load_model
    checkpoint = torch.load(model_path, map_location=torch.device('cpu'))
  File "/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.````

**Comment by ShunyaYamagami** [comment]
The cause of the error was that I had downloaded the file as an HTML file during `download_gdrive`.
I addressed this by downloading directly from GoogleDrive, `https://drive.google.com/u/0/uc?id=1t98aEuzeTL8P7Kpd5DIrCoCL21BNZUhC&export=download` as Standard.pt.

**Comment by daeunni** [comment]
@ShunyaYamagami  Hi, where did you find the exact url?

**Comment by ShunyaYamagami** [comment]
@daeunni 

I solved this a long time ago, so I am answering from hazy memory.

You might be able to donwload the correct file from this.
`https://drive.usercontent.google.com/download?id=1wy7gSRsUZzCzj8QhmTbcnwmES_2kkNph&export=download`

You can chech the gdrive id and check the URL with the following code.

`robustbench/model_zoo/cifar100.py`
```
    ('Hendrycks2020AugMix_WRN', {
        'model': Hendrycks2020AugMixWRNNet,
        'gdrive_id': '1XpFFdCdU9LcDtcyNfo6_BV1RZHKKkBVE'
    }),
```

```
import requests
session = requests.Session()
url_base = "https://docs.google.com/uc?export=download"
gdrive_id = '1XpFFdCdU9LcDtcyNfo6_BV1RZHKKkBVE'
response = session.get(url_base, params={'id': gdrive_id}, stream=True)
response.url
```

**Comment by daeunni** [comment]
Thanks for your quick reply!
